//
//  BackButtonStyleKit.swift
//  Movie Review
//
//  Created by  on 1/4/16.
//  Copyright (c) 2016 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class BackButtonStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let purple: UIColor = UIColor(red: 0.353, green: 0.235, blue: 0.663, alpha: 1.000)
        static var image32x44: UIImage?

    }

    //// Colors

    public class var purple: UIColor { return Cache.purple }

    //// Images

    public class var image32x44: UIImage {
        if Cache.image32x44 == nil {
            Cache.image32x44 = UIImage(named: "image32x44.png")!
        }
        return Cache.image32x44!
    }

    //// Drawing Methods

    public class func drawBackButton() {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(30.17, 12.5))
        bezierPath.addLineToPoint(CGPointMake(30.75, 12.5))
        bezierPath.addLineToPoint(CGPointMake(32.5, 14.26))
        bezierPath.addLineToPoint(CGPointMake(32.5, 14.84))
        bezierPath.addLineToPoint(CGPointMake(23.17, 24.21))
        bezierPath.addLineToPoint(CGPointMake(23.17, 24.79))
        bezierPath.addLineToPoint(CGPointMake(32.5, 34.16))
        bezierPath.addLineToPoint(CGPointMake(32.5, 34.74))
        bezierPath.addLineToPoint(CGPointMake(30.75, 36.5))
        bezierPath.addLineToPoint(CGPointMake(30.17, 36.5))
        bezierPath.addLineToPoint(CGPointMake(18.5, 24.79))
        bezierPath.addLineToPoint(CGPointMake(18.5, 24.21))
        bezierPath.addLineToPoint(CGPointMake(30.17, 12.5))
        bezierPath.closePath()
        BackButtonStyleKit.purple.setFill()
        bezierPath.fill()
        BackButtonStyleKit.purple.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

}
